<a href="https://colab.research.google.com/github/achu1293/PandaSeries/blob/main/Copy_of_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
list1 = [2,4,6,8]
value = pd.Series(list1)
print(value)

0    2
1    4
2    6
3    8
dtype: int64


In [ ]:
import pandas as pd
list1 = [2,4.5,9.5,'hi',40]
value = pd.Series(list1, index = ["a","b","c","d","e"])
print(value)

a      2
b    4.5
c    9.5
d     hi
e     40
dtype: object


In [ ]:
import pandas as pd
list1 = [2,4.5,9.5,'hi',40]
value = pd.Series(list1, index = ["a","b","c","d"])


ValueError: ignored

In [ ]:
import pandas as pd
list1 = [2,4.5,9.5,'hi',40]
value = pd.Series(list1, index = ["a","b","c","d","3"])

In [ ]:
import pandas as pd
dict1={"num12,4.5,9.5,'hi',40]
value = 

SyntaxError: ignored

In [ ]:
import pandas as pd
dict1={"num1":2,"num2":4.5,"num3":9.5,"string1":'hi',"num4":40}
value = pd.Series(dict1)
print(value)

num1         2
num2       4.5
num3       9.5
string1     hi
num4        40
dtype: object


In [ ]:
import pandas as pd
dict1={"num1":2,"num2":4.5,"num3":9.5,"string1":'hi',"num4":40}
value = pd.Series(dict1, index=['1','2','3','4','5'])
print(value)

1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
dtype: object


In [ ]:
import pandas as pd
dict1={"num1":2,"num2":4.5,"num3":9.5,"string1":'hi',"num4":40}
value = pd.Series(dict1, index=['num3','string3'])
print(value)

num3       9.5
string3    NaN
dtype: object


In [ ]:
import pandas as pd
dict1={"num1":2,"num2":4.5,"num3":9.5,"string1":'hi',"num4":40}
value = pd.Series(dict1, index=['num3','string1'])
print(value)

num3       9.5
string1     hi
dtype: object


In [ ]:
import pandas as pd
dict1 = { "name":['akash','sujatha','ramesh','ramya'], "age":[23,45,48,27]}
value1 = pd.DataFrame(dict1)
print(value1)

      name  age
0    akash   23
1  sujatha   45
2   ramesh   48
3    ramya   27


In [ ]:
import pandas as pd
list1 = [['akash','sujatha','ramesh','ramya'],[23,45,48,27]]
value1 = pd.DataFrame(list1,columns=['name','age'])
print(value1)

ValueError: ignored

In [ ]:
import pandas as pd
list1 = [['akash',23],['sujatha',45],['ramesh',48],['ramya',27]]
value1 = pd.DataFrame(list1,columns=['name','age'])
print(value1)

      name  age
0    akash   23
1  sujatha   45
2   ramesh   48
3    ramya   27


In [ ]:
import pandas as pd
dict1 = { "name":['akash','sujatha','ramesh','ramya'], "age":[23,45,48,27]}
value1 = pd.DataFrame(dict1,index=['101','102','103','104'])
print(value1)

        name  age
101    akash   23
102  sujatha   45
103   ramesh   48
104    ramya   27


In [ ]:
import pandas as pd
list1 = [2,4,6,8]
value = pd.Series(list1,dtype=float)
print(value)

0    2.0
1    4.0
2    6.0
3    8.0
dtype: float64


In [ ]:
import pandas as pd
list1 = [2,4.5,9.5,'hi',40]
value = pd.Series(list1, index = ["1","b","2","d","3"])
print(value)

1      2
b    4.5
2    9.5
d     hi
3     40
dtype: object


In [ ]:
import pandas as pd
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
print (s[:3])

a    1
b    2
c    3
dtype: int64


In [ ]:
import pandas as pd
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

#retrieve the last three element
print (s[-3:])

c    3
d    4
e    5
dtype: int64


In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

#select all rows for a specific column
#print df.loc[:,'A']
print(df)

          A         B         C         D
a  0.240545  0.660478  0.287213 -0.277696
b -1.408469  0.254260 -0.040451 -0.009050
c -0.822556  0.021977 -0.483849  0.956496
d  0.910601  1.163224 -0.839016  0.092027
e -1.374710  0.896588 -1.159534  0.701523
f -0.272903 -2.386611 -0.312843 -0.010683
g  0.933271  0.752049  0.320823 -0.289204
h -0.651757  0.207713  0.115299  1.438248


In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

#select all rows for a specific column
print(df)
#print (df.loc[:,'B'])
#

          A         B         C         D
a -2.245365  0.665765 -0.282798 -0.425807
b  0.520068 -0.515822 -0.815141 -0.576875
c  1.125746  1.012867 -0.233473 -0.821691
d -0.327485  0.119058  1.721709  0.525531
e  1.704992  0.821746 -1.927882  0.188166
f  0.360849  0.240164 -0.088183 -0.338080
g  0.783807 -0.654539  0.271650  0.292383
h  1.269227 -0.127144  0.162289 -0.285547


In [ ]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C'])

#select all rows for a specific column
print(df)

ValueError: ignored

In [ ]:
import random
print(random.randn(8,4))

AttributeError: ignored

In [ ]:
import random
import numpy as np
print(np.random.randn(8,4))

[[ 0.38962829 -0.67676252 -0.17800584 -1.57195046]
 [ 1.04770772  0.26933298  3.15440302 -1.78223758]
 [ 0.12015774 -0.35286902  0.24879988  0.31494087]
 [ 0.06558187 -0.92384436 -1.64411938 -1.16132522]
 [ 0.08691162  0.10728271  0.17350465 -1.42541559]
 [-1.45879959 -0.40630034  1.13773265 -0.26431342]
 [-1.04880723  1.84569626 -0.85816632 -0.3555635 ]
 [ 1.8249561   0.10061683  1.95564512 -1.50506147]]


In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])
print (df.loc[:,['B','A']])

          B         A
a  0.186105  1.608517
b -1.006968  0.040962
c -1.199195  1.738268
d -0.387919  1.260023
e  0.951331 -0.415968
f  1.101669 -0.457753
g -0.803073 -0.917705
h -1.406221  0.494158


In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b',','e','h'], columns = ['A', 'B', 'C'])
print (df.loc[:,['C','A']])

SyntaxError: ignored

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])
print (df.loc[['a','b','e','h'],['B','A']])

          B         A
a  0.227101 -0.604575
b -0.311488  1.015615
e  1.004294  0.364926
h  0.448725  1.330685


In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])
print (df.loc['a':'e'])

          A         B         C         D
a -0.916414 -2.267544  1.245668  0.491373
b -0.261728 -0.782771  2.041586  0.120303
c  1.070189  0.761597 -0.446219 -0.550990
d -1.364615 -0.340230 -0.299073 -0.341764
e -0.698237 -1.482750 -0.654954  0.015025


In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])
print (df.loc['a']>0)

A     True
B    False
C    False
D     True
Name: a, dtype: bool


In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
print (df.iloc[:4])
print (df.iloc[1:5, 2:4])

          A         B         C         D
0 -1.780452  1.304391  0.643524 -0.838940
1  1.006903  0.214076  0.405186  1.143013
2  1.699004 -0.889005 -0.007015 -0.183429
3  1.214999 -0.506916  0.307093 -1.633222
          C         D
1  0.405186  1.143013
2 -0.007015 -0.183429
3  0.307093 -1.633222
4 -0.608107 -0.297510


In [4]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
print (df.iloc[[1, 3, 5], [1, 3]])
print (df.iloc[1:3, :])
print (df.iloc[:,1:3])

          B         D
1 -1.021325  1.639772
3 -0.698386 -0.814316
5  0.183172 -1.264266
          A         B         C         D
1  1.429824 -1.021325 -0.772405  1.639772
2  1.494813 -0.059361 -0.030307 -0.955843
          B         C
0  0.280731 -0.698951
1 -1.021325 -0.772405
2 -0.059361 -0.030307
3 -0.698386  0.299539
4  1.576473 -0.007761
5  0.183172 -0.198422
6 -2.371932 -1.523856
7 -0.029654 -0.219651


In [7]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
print (df.ix[:4])

AttributeError: ignored

In [8]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f',
'h'],columns=['one', 'two', 'three'])
df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
print (df)


        one       two     three
a  0.356870 -0.047345 -0.284562
b       NaN       NaN       NaN
c  0.255638  0.963031 -0.597966
d       NaN       NaN       NaN
e  0.869896 -0.808101 -0.322780
f -0.896122 -0.076430  0.132475
g       NaN       NaN       NaN
h -0.269487 -0.561668 -0.436579
